### PR TITLE
Automatic citation generation

### PR DESCRIPTION
**Pull request by mphoward**
HOOMD should automatically notify the user when he uses a feature that requires citation (https://codeblue.umich.edu/hoomd-blue/doc/page_citing.html). This pull request implements this feature as a python module that creates a global bibliography. The bibliography always includes the two standard HOOMD citations, and individual features add citations on initialization. Each citation is reported to console as a level 1 notice with an optional feature descriptor, and multiple citations are grouped by feature. The user can also save the bibliography to a BibTeX file through cite.save(), which automatically updates the bibliography each time run() is called, or can optionally force a bibliography to file without calling run() (in case the user forgets to generate the file at runtime).

This pull request also addresses #42 (https://bitbucket.org/glotzer/hoomd-blue/issue/42/send-hoomd-startup-messages-through). Compilation startup messages are returned as a string, and displayed as a level 1 notice. When --notice-level=0, all non-warning/error output is suppressed.

### CODE REVIEW

**Comment by joaander** [comment]
Disclaimer: I haven't built and run the code yet.

This is a very complete and nice implementation of the proposed feature. I like it. I just have a few UX comments / suggestions for improvement.

1) save(file='hoomd.bib', overwrite=True, force=False) - this seems unnecessarily complex. Are there use cases where you think that users would want to set overwrite=False? Also, I would think that save() would always save the current state and then register the autosave feature to add any additional features that are used later in the script. This way, a user can put save('file.bib') at the end of the script or the beginning without having to think about the force and overwrite settings.

2) It seems that the citations are printed every time add() is called. Is that right? So if I call integrate.nvt_rigid, I get a print of 3 refs (2 base + rigid) - then in the next line I call pair.dpd I get another print with 4 refs (2 base + rigid + dpd). That seems a little chatty to me. Have you considered doing the print out at the beginning or end of every run()? Or registering an atexit routine to print once at the end of a job? Or tying the print to the screen to the autosave so that it is only printed once, or again if changed?

**Comment by mphoward** [comment]
1) What you propose is a much more natural interface, and I can't think of a common use case where you would want to stop overwriting. My original thought was to mimic analyze.log, but the bibliography is a different type of file output that should never be appended to in case of duplicate entries. I will revise the interface and behavior as you have proposed: save('file.bib') generates the file immediately with the current list of citations, and then autosave overwrites this file as new citations are added.

2) Only new citations are printed to screen as they are added, for example: 2 base citations are printed on import, the rigid citation is printed on construction of integrate.nvt_rigid, the dpd citation is printed when pair.dpd is constructed. That way, the user can see in the log file which citations correspond to which feature they used (citation appearing immediately after status line is printed). This seemed more helpful to me than printing them in a big batch. The list of all citations can always be dumped with save(). The only time this gets too chatty is if you create, say, an integrate.nvt_rigid and an integrate.nve_rigid, since the same citation will be printed to screen twice, but stored in the bib file only once. I thought this would be okay since (1) such a situation is probably not super common and (2) the user should still be aware that both integrators they've used require citation when they write a publication.

**Comment by mphoward** [comment]
Interface has been updated.

**Comment by joaander** [comment]
Excellent, thanks. The only thing I see missing at this point is an update to the credits documentation page.

**Comment by mphoward** [comment]
Will you do this after merge, or should I? And, given my other open PRs that will also need addition to the credits, do you want to do this all at once or incrementally with each?

**Pull request merged**
